image: fpco/stack-build:lts-9.10
stages:
  - deploy

pages:
  stage: deploy
  script:
  - apt-get install -y xz-utils pandoc ruby-compass
  - stack config set system-ghc --global true
  - scripts/ci/pages
  artifacts:
    paths:
    - public
  only:
  - release
