image: fpco/stack-build:lts-9.10
stages:
  - deploy

pages:
  stage: deploy
  script:
  - apt-get install -y xz-utils
  - STACK_FLAGS=--system-ghc scripts/ci/pages
  artifacts:
    paths:
    - public
  only:
  - release
