#!/bin/bash
IFSBAK="$IFS"
declare -A PKGS
while read pkg ver; do
    PKGS[$pkg]="$ver"
done < <(stack list-dependencies)
for file in */*.cabal; do
    while IFS= read line; do
        case "$line" in
            *build-depends:*)
                IFS="$IFS,&" deps=( ${line#*build-depends:} ) IFS="$IFSBAK"
                full_deps=( )
                for dep in "${deps[@]}"; do
                    case "$dep" in
                        '>'*|'<'*|'') :;;
                        *)
                            ver="${PKGS[$dep]}"
                            IFS=. vern=( $ver ) IFS="$IFSBAK"
                            full_deps+=( "$dep >=${vern[0]}.${vern[1]} && <${vern[0]}.$((vern[1]+1))" )
                            ;;
                    esac
                done
                IFS=$'\n' full_deps=( $(printf "%s\n" "${full_deps[@]}" | sort) ) IFS="$IFSBAK"
                IFS=,; printf "  build-depends: %s\n" "${full_deps[*]}"; IFS="$IFSBAK"
                ;;
            *) printf "%s\n" "$line";;
        esac
    done < "$file" > "$file.new"
    mv "$file"{.new,}
done
