#!/bin/bash
make -C curly/doc || exit
# make doc || exit
function has_cmd() { which "$1" 2>/dev/null; }

if has_cmd sass; then scss=sass
elif has_cmd sassc; then scss=sassc
elif has_cmd scss; then scss=scss
fi

mkdir -p public/doc && {
    packages=( )
    ispackage=
    while read line; do
        case "$line" in
            packages:*) ispackage=true;;
            -*) if [ "$ispackage" = true ]; then
                    packages+=( ${line#-} )
                fi;;
            *) ispackage=;;
        esac
    done < stack.yaml

    executables=( )
    for pkg in "${packages[@]}"; do
        executables+=( $(sed -rn 's/^executable\s+(\S+).*$/\1/p' "$pkg/$pkg.cabal" | grep -v '\.js$') )
    done
    stack_path="$(stack path --local-install-root)"
    
    cp "$stack_path"/doc/ocean.css public/doc
    {
        cat <<EOF
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="ocean.css" type="text/css" />
  </head>
  <body>
    <div id="package-header">
      <ul class="links">
        <li><a href="https://git.curly-lang.org/marc/curly">Source repository</a></li>
	<li><a href="../index.html">Back to the main page</a></li>
      </ul>
      <div class="caption">Curly packages</div></div>
    <div id="content">
      <h1>Curly packages</h1>
      <p>Here is a list of all local packages in the Curly repositories</p>
      <ul>
EOF
        for pkg in "${packages[@]}"; do
            fullpkg=( "$stack_path"/doc/$pkg-[0-9]* )
            fullpkg=( ${fullpkg[@]: -1:1} )
            fullpkg="${fullpkg##*/}"
            cp -r "$stack_path"/doc/$fullpkg public/doc
            if [ -e public/doc/$fullpkg/index.html ]; then
                printf '<li><a href="%s/index.html">%s</a></li>\n' "$fullpkg" "$pkg"
            fi
        done
        find public/doc -name src | xargs rm -r
        cat <<EOF
      </ul>
      <h2>Packages</h2>
      <ul>
EOF
        mkdir -p public/pkg
        for exe in "${executables[@]}"; do
	    version="$(sed -n 's/^version:\s*//p' "$exe/$exe.cabal")"
	    full="$exe-$version"
	    if [ ! -e public/pkg/$full.tar.xz ]; then
		curl -L "https://github.com/lih/stack-libs/releases/download/release-$full/$exe.linux.x86_64.tar.xz" \
		     > public/pkg/$full.tar.xz
	    fi
	    ln -fs $full.tar.xz public/pkg/$exe.tar.xz
            printf '<li><a href="pkg/%s.tar.xz">%s.tar.xz</a></li>\n' "$exe" "$full"
        done
        cat <<EOF
      </ul>
    </div>
  </body>
</html>
EOF
    } > public/doc/custom-index.html

    mkdir -p public
    tar -xvzf curly/doc/bundle.tar.gz -C public
}
