#!/bin/bash
make doc || exit
mkdir -p public && {
    packages=( )
    ispackage=
    while read line; do
        case "$line" in
            packages:*) ispackage=true;;
            -*) if [ "$ispackage" = true ]; then
                    packages+=( ${line#-} )
                fi;;
            *) ispackage=;;
        esac
    done < stack.yaml

    executables=( )
    for pkg in "${packages[@]}"; do
        executables+=( $(sed -rn 's/^executable\s+(\S+).*$/\1/p' "$pkg/$pkg.cabal") )
    done
    stack_path="$(stack path --local-install-root)"
    
    cp "$stack_path"/doc/ocean.css public
    {
        cat <<EOF
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="ocean.css" type="text/css" />
  </head>
  <body>
    <div id="package-header">
      <ul class="links">
        <li><a href="https://gricad-gitlab.univ-grenoble-alpes.fr/coiffiem/curly">Source repository</a></li>
	<li><a href="doc/index.html">Tutorial</a></li>
      </ul>
      <div class="caption">Curly packages</div></div>
    <div id="content">
      <h1>Curly packages</h1>
      <p>Here is a list of all local packages in the Curly repositories</p>
      <ul>
EOF
        for pkg in "${packages[@]}"; do
            fullpkg=( "$stack_path"/doc/$pkg-[0-9]* )
            fullpkg=( ${fullpkg[@]: -1:1} )
            fullpkg="${fullpkg##*/}"
            cp -r "$stack_path"/doc/$fullpkg public
            if [ -e public/$fullpkg/index.html ]; then
                printf '<li><a href="%s/index.html">%s</a></li>\n' "$fullpkg" "$pkg"
            fi
        done
        find public -name src | xargs rm -r
        cat <<EOF
      </ul>
      <h2>Packages</h2>
      <ul>
EOF
        mkdir -p public/pkg
        for exe in "${executables[@]}"; do
	    version="$(sed -n 's/^version:\s*//p' "$exe/$exe.cabal")"
	    full="$exe-$version"
	    shopt -s nullglob
	    (
	    	tmp="$(mktemp -d)"
	    	mkdir -p "$tmp/$full"
	    	cd "$stack_path"
	    	cp -r bin/$exe share/*/$exe-*/* "$tmp/$full"
	    	tar -C "$tmp" -c .
	    	rm -r "$tmp"
	    ) | xz > public/pkg/$exe.tar.xz
            printf '<li><a href="pkg/%s.tar.xz">%s.tar.xz</a></li>\n' "$exe" "$full"
        done
        cat <<EOF
      </ul>
    </div>
  </body>
</html>
EOF
    } > public/index.html

    shopt -s globstar
    mkdir -p "public/doc"
    for i in curly/doc/**/*.md; do
	rel="${i#curly/doc}"
	mkdir -p "public/doc${rel%/*}"
	pandoc -s --toc --template="curly/doc/template.html" --css "style.css" -o "public/doc${rel/%.md/.html}" "$i"
    done
    sassc curly/doc/style.scss > public/doc/style.css
    cp curly/doc/{Titillium.woff2,Roboto.woff2} public/doc/
}
