#!/bin/bash
function C.curly() {
    local -a CURLY_COMP_SCRIPTS=( )
    local which_curly="$(which "${COMP_PROGRAM/icy/curly}")"
    case "$which_curly" in
	/usr/bin/*) ;;
	*) CURLY_COMP_SCRIPTS=( "$which_curly" );;
    esac
    C.repeat C.curly.arg
}
C.curly "$@"
