#!/bin/bash
notify-send "Stack: Compilation completed successfully"

if [ ! -e .autocommit ]; then
    git branch autocommit || :
    git clone -b autocommit . .autocommit
fi
GIT_DIR=.autocommit/.git git commit -am "Successful build (on $(date))"
GIT_DIR=.autocommit/.git git push 
notify-send "New commit pushed to the autocommit branch"
