#!/bin/bash
make doc || exit
mkdir -p public && {
    packages=( )
    ispackage=
    while read line; do
        case "$line" in
            packages:*) ispackage=true;;
            -*) if [ "$ispackage" = true ]; then
                    packages+=( ${line#-} )
                fi;;
            *) ispackage=;;
        esac
    done < stack.yaml
    
    cp .stack-work/install/*/*/*/doc/ocean.css public
    {
        cat <<EOF
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="ocean.css" type="text/css" />
  </head>
  <body>
    <div id="package-header">
      <ul class="links">
        <li><a href="https://gricad-gitlab.univ-grenoble-alpes.fr/coiffiem/curly">Source repository</a></li>
      </ul>
      <div class="caption">Curly packages</div></div>
    <div id="content">
      <h1>Curly packages</h1>
      <p>Here is a list of all local packages in the Curly repositories</p>
      <ul>
EOF
        for pkg in "${packages[@]}"; do
            fullpkg=( .stack-work/install/*/*/*/doc/$pkg-[0-9]* )
            fullpkg=( ${fullpkg[@]: -1:1} )
            fullpkg="${fullpkg##*/}"
            cp -r .stack-work/install/*/*/*/doc/$fullpkg public
            if [ -e public/$fullpkg/index.html ]; then
                printf '<li><a href="%s/index.html">%s</a></li>\n' "$fullpkg" "$pkg"
            fi
        done
        find public -name src | xargs rm -r
        cat <<EOF
      </ul>
    </div>
  </body>
</html>
EOF
    } > public/index.html
}
